### ISSUE TITLE
Move Module-related functions from System to Module file

### ISSUE THREAD

**Issue by AlexSkrypnyk** [nicksantamaria/drupal_helpers#10]

**Comment by nicksantamaria** [comment]
@alexdesignworks which functions are you referring to? All of the functions are applicable to modules, themes and profiles.

If anything, probably best to remove the default parameter values in the `System` class (all of which are currently set to `'module'`).

**Comment by AlexSkrypnyk** [comment]
@nicksantamaria I looked closer to `System` class and it looks like that it is shared across `Theme` and `Module` classes, so this issue is no longer applicable.

But, we probably should consider to making `System` class private and exposing methods within respected classes.
